spring.application.name=clinic-backend
server.port=8888

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-tight-block-a83wk7n1-pooler.eastus2.azure.neon.tech/clinic_db?sslmode=require&channel_binding=require
spring.datasource.username=clinic_db_owner
spring.datasource.password=npg_T79ACcFZhuHU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Minio SDK Configuration
minio.url=b5l0.or.idrivee2-33.com
minio.access-key=7upuUIHza0UiAJmUkosI
minio.secret-key=uFrRIE0iWhDBRW9cMXE7FAwlLze4BahxZ6041Gfm
minio.bucket-name=clinical-management

# JWT Configuration
# IMPORTANT: Replace this placeholder with a strong, securely generated and stored secret key!
application.security.jwt.secret-key=placeholderSecretKeyThatIsVeryLongAndSecure1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

#Javamail configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=${MAIL_PROTOCOL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

api.prefix=api/v1