spring.application.name=clinic-backend
server.port=9090
api.prefix=/api/v1

# Database Configuration (Local PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-tight-block-a83wk7n1-pooler.eastus2.azure.neon.tech/clinic_db?sslmode=require&channel_binding=require
spring.datasource.username=clinic_db_owner
spring.datasource.password=npg_T79ACcFZhuHU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Minio SDK Configuration (adapter si besoin)
#minio.url=${MINIO_API_URL}
#minio.access-key=${MINIO_USERNAME}
#minio.secret-key=${MINIO_PASSWORD}
#minio.bucket-name=${MINIO_PROJECT_NAME}

minio.url=b5l0.or.idrivee2-33.com
minio.access-key=7upuUIHza0UiAJmUkosI
minio.secret-key=uFrRIE0iWhDBRW9cMXE7FAwlLze4BahxZ6041Gfm
minio.bucket-name=clinical-management

# JWT Configuration
application.security.jwt.secret-key=placeholderSecretKeyThatIsVeryLongAndSecure1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
