package com.clinicapp.backend.model.notification;

public enum NotificationType {
    NEW_OFFER,
    NEW_APPLICATION,
    CONVENTION_VALIDATION,
    ADMIN_APPROVAL,
    CONVENTION_VALIDATION_REMINDER,
    APPLICATION_DECISION_REMINDER,
    NEW_APPOINTMENT,
    NEW_PRESCRIPTION,
    NEW_INVOICE,
    NEW_PATIENT,
    UPDATE_PATIENT,
    NEW_CHAT_MESSAGE
}
